version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3316:3316"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always
